### PR TITLE
Store and reducers use in Components

### PR DESCRIPTION
**Pull request by frempongdev**
### - Implemented Redux store and reducers in React Components. ♻️ 
  - Added books initialState. {...}
  - Displayed  books, received from the slice, in a reusable component
  - Dispatched actions using useDispatch
  - Added a <Button> component, which includes event handler that adds a book to the books array (with attributes id, title and author). 🖱️ 
  - Added a <Button> component, which includes event handler that removes a book from the books array (by id) 🖱️ 
  - Added a <Button> component, which includes event handler that checks status. 🖱️ 
  - Fixed Linter errors 🧰

### CODE REVIEW

**Review by brytebee — CHANGES_REQUESTED** [review]
Hi, @frempongdev👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great README.✔️
- No linter errors✔️

##

Good job so far coming so far with the progress you've made! 💪💪
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!



# Required Changes ♻️

 - Kindly fix these error that prevents your app from running. Kindly note that the capitalization used in the file path is not the same as that in the import statement. Kindly fix this.
 
 
image


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by frempongdev** [comment]
hi @brytebee 
There seemed to be an issue with the change of file name in this repo. 
image


However, i have fixed this error here on GitHub.

Thank you for drawing my attention.

**Review by iambenkis — APPROVED** [review]
Hi @frempongdev ,

## APPROVED 🟢

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by frempongdev** [comment]
@iambenkis @brytebee ,
Thank You for your review and kind words.

**Pull request merged**
